### ISSUE TITLE
The documentation of the gate MODMUL()

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#101]
Here is a code snippet from the [shor example](https://github.com/softwareQinc/qpp/blob/main/examples/shor.cpp).

```
    for (idx i = 0; i < n; ++i) {
        // compute 2^(n-i-1) mod N
        idx j = static_cast<idx>(std::llround(std::pow(2, n - i - 1)));
        // compute the a^(2^(n-i-1)) mod N
        idx aj = modpow(a, j, N);
        // apply the controlled modular multiplication
        psi = applyCTRL(psi, gt.MODMUL(aj, N, n), {i}, second_subsys);
    }
```

That shows how to use the `gt.MODMUL()` properly.

The doc says something like this:

> **Note**
> ... a and N should be co-prime. 
> 
> **Parameters**
> **a**    Positive integer less than N

The `a `in the documentation basically means the `aj `in the code, doesn't it? Since the gate does not check co-primality, it is the user's responsibility to make sure the argument such as `modpow(a, j, N)` is a co-prime of `N`. Is that correct?

**Comment by vsoftco** [comment]
I think the documentation is correct, and the usage is correct as well. First, `aj = modpow(a, j, N)` computes $a^j mod N$, which is smaller than N since we compute it mod D. Next, since $a$ and $N$ are coprime, then also $a^j$ (i.e., `aj` in the code) is coprime with N (that because powers $a^j$ of $a$ have the same prime factors as $a$). So there's no need for manual co-primality checks, it's guaranteed by the math.

**Comment by DevelopDaily** [comment]
Yes, very clear now.

I didn't realize that is guaranteed by math at first glance. Thanks for the enlightenment.
